In [1]:
import numpy as np

# ---- 例1：旋转90度 ----
# 变换: T(x, y) = (-y, x)（逆时针旋转90度）
def T_rot90(v):
    return np.array([-v[1], v[0]])

# 输入基：标准基 e1=(1,0), e2=(0,1)
e1 = np.array([1, 0])
e2 = np.array([0, 1])

# 计算 T(e1) 和 T(e2)
T_e1 = T_rot90(e1)  # (0, 1)
T_e2 = T_rot90(e2)  # (-1, 0)

# 矩阵的列就是这些结果
A_rot90 = np.column_stack([T_e1, T_e2])
print("=" * 60)
print("从变换到矩阵")
print("=" * 60)
print(f"旋转90度变换的矩阵:\n{A_rot90}")

# 验证
v = np.array([3, 1])
print(f"\nv = {v}")
print(f"T(v) = {T_rot90(v)}")
print(f"A @ v = {A_rot90 @ v}")

# ---- 例2：投影到x轴 ----
def T_proj_x(v):
    return np.array([v[0], 0])

T_e1_proj = T_proj_x(e1)  # (1, 0)
T_e2_proj = T_proj_x(e2)  # (0, 0)
A_proj = np.column_stack([T_e1_proj, T_e2_proj])
print(f"\n投影到x轴的矩阵:\n{A_proj}")
print(f"A @ v = {A_proj @ v}")

# ---- 例3：在非标准基下的矩阵 ----
# 变换: 在基 B 的列向量张成的坐标系中，T 是旋转90度
# 在标准基下，这个变换的矩阵是 B @ R @ B^{-1}
B = np.array([[1, 1], [0, 2]])  # 任意基
R = np.array([[0, -1], [1, 0]])  # 旋转90度（在B基下）
A_B = B @ R @ np.linalg.inv(B)
print(f"\n在非标准基下旋转90度的矩阵:\n{A_B.round(3)}")

从变换到矩阵
旋转90度变换的矩阵:
[[ 0 -1]
 [ 1  0]]

v = [3 1]
T(v) = [-1  3]
A @ v = [-1  3]

投影到x轴的矩阵:
[[1 0]
 [0 0]]
A @ v = [3 0]

在非标准基下旋转90度的矩阵:
[[ 1. -1.]
 [ 2. -1.]]
