In [ ]:
import numpy as np

# ---- 一个 3x3 的线性方程组 ----
# 方程：
#  x + 2y +  z = 2
# 3x + 8y +  z = 12
# 0x + 4y +  z = 2

A = np.array([[1, 2, 1],
              [3, 8, 1],
              [0, 4, 1]], dtype=float)
b = np.array([2, 12, 2], dtype=float)

print("原始矩阵 A:")
print(A)
print("右端项 b:", b)

# ---- 用 np.linalg.solve 直接求解（它内部就是消元法） ----
x = np.linalg.solve(A, b)
print(f"\n方程的解: x = {x}")

# ---- 手动消元演示：只保留关键步骤 ----
# 步骤1：用第1行消去第2行的第一个元素
# 倍数 = 3/1 = 3
print("\n=== 消元步骤 ===")
print("步骤1: 第2行 - 3 * 第1行")
A[1, :] = A[1, :] - 3 * A[0, :]
b[1] = b[1] - 3 * b[0]
print("A 变为:\n", A)
print("b 变为:", b)

# 步骤2：现在第2行已经是 [0, 2, -2]，用它消去第3行的第二个元素
# 第3行的第2个元素是4，第2行的第2个元素是2，倍数是 4/2 = 2
print("\n步骤2: 第3行 - 2 * 第2行")
A[2, :] = A[2, :] - 2 * A[1, :]
b[2] = b[2] - 2 * b[1]
print("A 变为:\n", A)  # 现在是上三角！
print("b 变为:", b)

# ---- 回代求解 ----
# 现在 A 是上三角：
# [1, 2, 1]   [x]   [2]
# [0, 2, -2]  [y] = [6]
# [0, 0, 5]   [z]   [-10]

print("\n=== 回代求解 ===")
z = b[2] / A[2, 2]  # 5z = -10 → z = -2
y = (b[1] - A[1, 2] * z) / A[1, 1]  # 2y - 2*-2 = 6 → 2y = 2  → y = 1
x = (b[0] - A[0, 1] * y - A[0, 2] * z) / A[0, 0]  # x + 2*1 + 1*-2 = 2 → x = 2
print(f"回代结果: x = {x}, y = {y}, z = {z}")

原始矩阵 A:
[[1. 2. 1.]
 [3. 8. 1.]
 [0. 4. 1.]]
右端项 b: [ 2. 12.  2.]

方程的解: x = [ 2.  1. -2.]

=== 消元步骤 ===
步骤1: 第2行 - 3 * 第1行
A 变为:
 [[ 1.  2.  1.]
 [ 0.  2. -2.]
 [ 0.  4.  1.]]
b 变为: [2. 6. 2.]

步骤2: 第3行 - 2 * 第2行
A 变为:
 [[ 1.  2.  1.]
 [ 0.  2. -2.]
 [ 0.  0.  5.]]
b 变为: [  2.   6. -10.]

=== 回代求解 ===
回代结果: x = 2.0, y = 1.0, z = -2.0
