In [20]:
'''1. 创建一组正交向量（用 Gram-Schmidt），验证它们两两正交。
2. 用投影矩阵 `P = A (A^T A)^{-1} A^T` 投影一个向量到列空间上。
3. 用 QR 分解（`np.linalg.qr`）解一个最小二乘问题，验证结果与 `np.linalg.lstsq` 一致。
'''

import numpy as np

# 1. 创建一组正交向量（用 Gram-Schmidt），验证它们两两正交。
A = np.random.randn(3, 3)
print('rank(A):\n', np.linalg.matrix_rank(A))
Q, R = np.linalg.qr(A)
print('Q:\n', Q)
print(f'q1 cdot q2 = {np.dot(Q[:, 0], Q[:, 1])}')
print(f'q1 cdot q3 = {np.dot(Q[:, 0], Q[:, 2])}')
print(f'q2 cdot q3 = {np.dot(Q[:, 1], Q[:, 2])}')

# 2. 用投影矩阵 `P = A (A^T A)^{-1} A^T` 投影一个向量到列空间上。
b = np.random.randn(3)
P = A @ np.linalg.inv(A.T @ A) @ A.T
print('P:\n', P)
print('P @ b:\n', P @ b)

# 3. 用 QR 分解（`np.linalg.qr`）解一个最小二乘问题，验证结果与 `np.linalg.lstsq` 一致。
print('='*50)
print('Use np.linalg.lstsq')
print('='*50)
b = np.random.randn(3)
x_lstsq, residuals_lstsq, rank_lstsq, s_lstsq = np.linalg.lstsq(A, b, rcond=None)
print('x:\n', x_lstsq)
print('residuals:\n', residuals_lstsq)
print('rank:\n', rank_lstsq)
print('s:\n', s_lstsq)

# QR 分解：QRx = b,Rx = Q^Tb
print('='*50)
print('Use QR decomposition')
print('='*50)
Q, R = np.linalg.qr(A)
x_qr = np.linalg.solve(R, Q.T @ b)
p_qr = A @ x_qr
e_qr = b - p_qr
print('x:\n', x_qr)
print('Project(p) :\n', p_qr)
print('Residual(e) :\n', e_qr)
print('Residual norm :\n', np.linalg.norm(e_qr, ord=2))
print('Rank :\n', np.linalg.matrix_rank(Q))

rank(A):
 3
Q:
 [[-0.31683395 -0.91398915  0.25345628]
 [ 0.78053527 -0.40307141 -0.47780553]
 [ 0.53887005  0.04644655  0.84110748]]
q1 cdot q2 = -3.5041414214731503e-16
q1 cdot q3 = 0.0
q2 cdot q3 = 8.326672684688674e-17
P:
 [[ 1.00000000e+00 -4.78248992e-17  8.40104705e-17]
 [-1.51200892e-16  1.00000000e+00 -3.02622570e-17]
 [ 4.93578864e-17  5.18331915e-18  1.00000000e+00]]
P @ b:
 [ 0.36639786  1.30910561 -0.4847868 ]
Use np.linalg.lstsq
x:
 [-0.28186325  0.50587102  0.6299092 ]
residuals:
 []
rank:
 3
s:
 [3.01190823 1.91029665 1.1087736 ]
Use QR decomposition
x:
 [-0.28186325  0.50587102  0.6299092 ]
Project(p) :
 [ 0.71265464  0.22246034 -0.96781828]
Residual(e) :
 [-2.22044605e-16 -1.38777878e-16  2.22044605e-16]
Residual norm :
 3.433175098891678e-16
Rank :
 3
