In [1]:
import numpy as np
import matplotlib.pyplot as plt

# ---- 输入：一组线性无关的向量 ----
a1 = np.array([1, 1, 0])
a2 = np.array([1, 0, 1])
a3 = np.array([0, 1, 1])

print("=" * 60)
print("Gram-Schmidt 正交化")
print("=" * 60)
print("原始向量:")
print(f"a1 = {a1}")
print(f"a2 = {a2}")
print(f"a3 = {a3}")

# ---- Gram-Schmidt 过程 ----
# 步骤1：第一个正交向量
q1 = a1 / np.linalg.norm(a1)

# 步骤2：第二个正交向量（减去在 q1 上的投影）
proj_q1_a2 = np.dot(a2, q1) * q1
v2 = a2 - proj_q1_a2
q2 = v2 / np.linalg.norm(v2)

# 步骤3：第三个正交向量（减去在 q1 和 q2 上的投影）
proj_q1_a3 = np.dot(a3, q1) * q1
proj_q2_a3 = np.dot(a3, q2) * q2
v3 = a3 - proj_q1_a3 - proj_q2_a3
q3 = v3 / np.linalg.norm(v3)

print("\n正交化后的向量:")
print(f"q1 = {q1.round(3)}")
print(f"q2 = {q2.round(3)}")
print(f"q3 = {q3.round(3)}")

# ---- 验证正交性 ----
print("\n验证正交性（点积应该为0）:")
print(f"q1·q2 = {np.dot(q1, q2):.6f}")
print(f"q1·q3 = {np.dot(q1, q3):.6f}")
print(f"q2·q3 = {np.dot(q2, q3):.6f}")

# ---- 验证单位长度 ----
print(f"\n||q1|| = {np.linalg.norm(q1):.6f}")
print(f"||q2|| = {np.linalg.norm(q2):.6f}")
print(f"||q3|| = {np.linalg.norm(q3):.6f}")

# ---- 组装成正交矩阵 Q ----
Q = np.column_stack([q1, q2, q3])
print(f"\nQ = \n{Q.round(3)}")
print(f"Q^T Q = \n{(Q.T @ Q).round(3)}")  # 应该是 I

# ---- 用 np.linalg.qr 验证 ----
Q_np, R_np = np.linalg.qr(np.column_stack([a1, a2, a3]))
print(f"\n用 np.linalg.qr 验证:")
print(f"Q 的第一列: {Q_np[:, 0].round(3)}")
print(f"Q 的第二列: {Q_np[:, 1].round(3)}")
print(f"Q 的第三列: {Q_np[:, 2].round(3)}")
print("（注意：符号可能不同，但方向相同）")

Gram-Schmidt 正交化
原始向量:
a1 = [1 1 0]
a2 = [1 0 1]
a3 = [0 1 1]

正交化后的向量:
q1 = [0.707 0.707 0.   ]
q2 = [ 0.408 -0.408  0.816]
q3 = [-0.577  0.577  0.577]

验证正交性（点积应该为0）:
q1·q2 = 0.000000
q1·q3 = 0.000000
q2·q3 = -0.000000

||q1|| = 1.000000
||q2|| = 1.000000
||q3|| = 1.000000

Q = 
[[ 0.707  0.408 -0.577]
 [ 0.707 -0.408  0.577]
 [ 0.     0.816  0.577]]
Q^T Q = 
[[ 1.  0.  0.]
 [ 0.  1. -0.]
 [ 0. -0.  1.]]

用 np.linalg.qr 验证:
Q 的第一列: [-0.707 -0.707 -0.   ]
Q 的第二列: [ 0.408 -0.408  0.816]
Q 的第三列: [-0.577  0.577  0.577]
（注意：符号可能不同，但方向相同）
