In [1]:
import numpy as np

# 案例1：有解的情况
A1 = np.array([[1, 2], [2, 4]])  # 列2 = 2 * 列1
b1 = np.array([3, 6])            # b1 = 3 * 列1，所以 b1 在列空间内（一条直线上）

print("案例1：")
print("A1 = \n", A1)
print("b1 =", b1)

# 计算秩
rank_A1 = np.linalg.matrix_rank(A1)
print(f"A1 的秩: {rank_A1}")  # 输出 1，说明列空间是一维的

# 检查 b1 是否在列空间内：通过解方程判断
try:
    x1 = np.linalg.solve(A1, b1)  # 尝试解方程
    print(f"✅ 有解！x = {x1}")
except np.linalg.LinAlgError:
    print("❌ 无解！")

# 案例2：无解的情况
b2 = np.array([3, 7])            # b2 不在列空间内
print("\n案例2：")
print("A1 = \n", A1)
print("b2 =", b2)

try:
    x2 = np.linalg.solve(A1, b2)
    print(f"✅ 有解！x = {x2}")
except np.linalg.LinAlgError:
    print("❌ 无解！b2 不在列空间内")

# 案例3：满秩的情况（列空间是二维的，即整个 R²）
A3 = np.array([[1, 2], [3, 4]])  # 两列线性无关，秩 = 2
b3 = np.array([5, 11])
print("\n案例3：")
print("A3 = \n", A3)
print("b3 =", b3)
print(f"A3 的秩: {np.linalg.matrix_rank(A3)}")  # 输出 2，列空间是整个平面

x3 = np.linalg.solve(A3, b3)
print(f"✅ 有解！x = {x3}")
print(f"验证: A3 @ x3 = {A3 @ x3}")

案例1：
A1 = 
 [[1 2]
 [2 4]]
b1 = [3 6]
A1 的秩: 1
❌ 无解！

案例2：
A1 = 
 [[1 2]
 [2 4]]
b2 = [3 7]
❌ 无解！b2 不在列空间内

案例3：
A3 = 
 [[1 2]
 [3 4]]
b3 = [ 5 11]
A3 的秩: 2
✅ 有解！x = [1. 2.]
验证: A3 @ x3 = [ 5. 11.]
