In [1]:
import numpy as np

print("=" * 60)
print("行列式性质验证")
print("=" * 60)

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print(f"A = \n{A}")
print(f"B = \n{B}")
print(f"det(A) = {np.linalg.det(A):.2f}")
print(f"det(B) = {np.linalg.det(B):.2f}")

# ---- 性质1：det(AB) = det(A) * det(B) ----
AB = A @ B
det_AB = np.linalg.det(AB)
det_A_times_B = np.linalg.det(A) * np.linalg.det(B)
print(f"\n性质1: det(AB) = {det_AB:.2f}")
print(f"det(A) * det(B) = {det_A_times_B:.2f}")
print(f"相等？ {np.isclose(det_AB, det_A_times_B)}")

# ---- 性质2：行交换改变符号 ----
A_swapped = A[[1, 0], :]  # 交换行
print(f"\n性质2: 行交换")
print(f"det(A) = {np.linalg.det(A):.2f}")
print(f"det(行交换后) = {np.linalg.det(A_swapped):.2f}")
print(f"符号相反？ {np.isclose(np.linalg.det(A_swapped), -np.linalg.det(A))}")

# ---- 性质3：行缩放 ----
c = 3
A_scaled = c * A
print(f"\n性质3: 行缩放")
print(f"det({c}A) = {np.linalg.det(A_scaled):.2f}")
print(f"{c}^{A.shape[0]} * det(A) = {c**A.shape[0] * np.linalg.det(A):.2f}")
print(f"相等？ {np.isclose(np.linalg.det(A_scaled), c**A.shape[0] * np.linalg.det(A))}")

# ---- 性质4：det(A) = 0 ⇔ 矩阵奇异 ----
A_singular = np.array([[1, 2], [2, 4]])  # 第二行 = 2 * 第一行
print(f"\n性质4: 奇异矩阵")
print(f"A_singular = \n{A_singular}")
print(f"det(A_singular) = {np.linalg.det(A_singular):.2f}")
print(f"矩阵奇异吗？ {np.isclose(np.linalg.det(A_singular), 0)}")

# ---- 性质5：det(A^T) = det(A) ----
print(f"\n性质5: det(A^T) = det(A)")
print(f"det(A) = {np.linalg.det(A):.2f}")
print(f"det(A^T) = {np.linalg.det(A.T):.2f}")
print(f"相等？ {np.isclose(np.linalg.det(A), np.linalg.det(A.T))}")

行列式性质验证
A = 
[[1 2]
 [3 4]]
B = 
[[5 6]
 [7 8]]
det(A) = -2.00
det(B) = -2.00

性质1: det(AB) = 4.00
det(A) * det(B) = 4.00
相等？ True

性质2: 行交换
det(A) = -2.00
det(行交换后) = 2.00
符号相反？ True

性质3: 行缩放
det(3A) = -18.00
3^2 * det(A) = -18.00
相等？ True

性质4: 奇异矩阵
A_singular = 
[[1 2]
 [2 4]]
det(A_singular) = 0.00
矩阵奇异吗？ True

性质5: det(A^T) = det(A)
det(A) = -2.00
det(A^T) = -2.00
相等？ True
