In [1]:
import numpy as np
from scipy.linalg import svd

# ---- 创建一个奇异矩阵 ----
A = np.array([[1, 2, 3], [2, 4, 6]])  # 秩为1
print("=" * 60)
print("伪逆 (Pseudoinverse)")
print("=" * 60)
print("A = \n", A)
print(f"秩: {np.linalg.matrix_rank(A)}")

# ---- SVD ----
U, S, Vt = svd(A, full_matrices=False)
print(f"\nSVD 结果:")
print(f"  U = \n{U.round(3)}")
print(f"  S = {S}")
print(f"  V^T = \n{Vt.round(3)}")

# ---- 构建伪逆 ----
# 计算 Σ^+
S_plus = np.array([1/s if s > 1e-10 else 0 for s in S])
# A^+ = V @ Σ^+ @ U^T
A_pinv = Vt.T @ np.diag(S_plus) @ U.T
print(f"\n伪逆 A^+ = \n{A_pinv.round(3)}")

# ---- 验证: A @ A^+ @ A = A ----
check1 = A @ A_pinv @ A
print(f"\nA @ A^+ @ A = \n{check1.round(3)}")
print(f"等于 A？ {np.allclose(check1, A)}")

# ---- 验证: A^+ @ A @ A^+ = A^+ ----
check2 = A_pinv @ A @ A_pinv
print(f"\nA^+ @ A @ A^+ = \n{check2.round(3)}")
print(f"等于 A^+？ {np.allclose(check2, A_pinv)}")

# ---- 用伪逆解最小二乘 ----
b = np.array([1, 2])
x_pinv = A_pinv @ b
print(f"\n用伪逆解 Ax = b (b={b}):")
print(f"  x = {x_pinv}")
print(f"  A @ x = {A @ x_pinv}")

# 验证 A@x 是列空间中最接近 b 的点
x_lstsq = np.linalg.lstsq(A, b, rcond=None)[0]
print(f"\n用 np.linalg.lstsq 得到的解: {x_lstsq}")
print(f"两者一致？ {np.allclose(x_pinv, x_lstsq)}")

伪逆 (Pseudoinverse)
A = 
 [[1 2 3]
 [2 4 6]]
秩: 1

SVD 结果:
  U = 
[[-0.447 -0.894]
 [-0.894  0.447]]
  S = [8.36660027e+00 5.61733355e-16]
  V^T = 
[[-0.267 -0.535 -0.802]
 [ 0.945 -0.309 -0.109]]

伪逆 A^+ = 
[[0.014 0.029]
 [0.029 0.057]
 [0.043 0.086]]

A @ A^+ @ A = 
[[1. 2. 3.]
 [2. 4. 6.]]
等于 A？ True

A^+ @ A @ A^+ = 
[[0.014 0.029]
 [0.029 0.057]
 [0.043 0.086]]
等于 A^+？ True

用伪逆解 Ax = b (b=[1 2]):
  x = [0.07142857 0.14285714 0.21428571]
  A @ x = [1. 2.]

用 np.linalg.lstsq 得到的解: [0.07142857 0.14285714 0.21428571]
两者一致？ True
