In [7]:
'''1. 创建一个 3x3 的随机矩阵，计算它的行列式。改变一个元素，观察行列式的变化。
2. 创建两个 2x2 矩阵，验证 $det(AB) = det(A) * det(B)$。
3. 创建一个接近奇异的矩阵，比较 $det$ 和条件数，哪个更能反映矩阵的“病态”程度？'''

import numpy as np

# 1. 创建一个 3x3 的随机矩阵，计算它的行列式。改变一个元素，观察行列式的变化。
A = np.random.rand(3, 3)
det_A = np.linalg.det(A)
print("Original matrix A:\n", A)
print("Determinant of A:", det_A)

# 改变一个元素
A[1, 1] = 0.5
det_A_modified = np.linalg.det(A)
print("Modified matrix A:\n", A)
print("Determinant of modified A:", det_A_modified)

# 2. 创建两个 2x2 矩阵，验证 $det(BC) = det(B) * det(C)$。
B = np.array([[1, 2], [3, 4]])
C = np.array([[5, 6], [7, 8]])

det_BC = np.linalg.det(np.dot(B, C))
det_B = np.linalg.det(B)
det_C = np.linalg.det(C)

print("Determinant of B:", det_B)
print("Determinant of C:", det_C)
print("Determinant of BC:", det_BC)
print("Verification:", np.allclose(det_BC, det_B * det_C))

# 3. 创建一个接近奇异的矩阵，比较 $det$ 和条件数，哪个更能反映矩阵的“病态”程度？
D = np.array([[1, 1], [1, 1.0001]])
det_D = np.linalg.det(D)
cond_D = np.linalg.cond(D)

print("Matrix D:\n", D)
print("Determinant of D:", det_D)
print("Condition number of D:", cond_D)

Original matrix A:
 [[0.83728836 0.29328352 0.34064558]
 [0.87685389 0.8855692  0.56235765]
 [0.1478887  0.35917482 0.49652042]]
Determinant of A: 0.15841301659871063
Modified matrix A:
 [[0.83728836 0.29328352 0.34064558]
 [0.87685389 0.5        0.56235765]
 [0.1478887  0.35917482 0.49652042]]
Determinant of modified A: 0.017544101194296637
Determinant of B: -2.0000000000000004
Determinant of C: -2.000000000000005
Determinant of BC: 4.000000000000008
Verification: True
Matrix D:
 [[1.     1.    ]
 [1.     1.0001]]
Determinant of D: 9.99999999999889e-05
Condition number of D: 40002.00007491187
