In [1]:
import numpy as np

# ---- 一维投影：投影到列向量 a 上 ----
a = np.array([1, 2, 2])
print("=" * 60)
print("一维投影矩阵")
print("=" * 60)
print(f"a = {a}")

# 投影矩阵 P = (a a^T) / (a^T a)
P1 = np.outer(a, a) / np.dot(a, a)
print(f"\nP = (a a^T) / (a^T a) =\n{P1}")

# 投影到 a 上
b = np.array([1, 1, 1])
p = P1 @ b
print(f"\nb = {b}")
print(f"投影 p = {p}")
print(f"验证: p 是 a 的倍数吗？{p / a[0]}")
print(f"误差 e = b - p = {b - p}")
print(f"e·a = {np.dot(b - p, a)} (应为0)")

# ---- 高维投影：投影到 A 的列空间 ----
print("\n" + "=" * 60)
print("高维投影矩阵")
print("=" * 60)

A = np.array([
    [1, 0],
    [1, 1],
    [1, 2]
])
b = np.array([1, 2, 2])

print("A = \n", A)
print(f"b = {b}")

# 投影矩阵 P = A (A^T A)^{-1} A^T
ATA = A.T @ A
P2 = A @ np.linalg.inv(ATA) @ A.T
print(f"\nP = A (A^T A)^{-1} A^T =\n{P2.round(3)}")

# 投影
p = P2 @ b
print(f"\n投影 p = {p.round(3)}")

# ---- 验证投影矩阵的性质 ----
print("\n" + "=" * 60)
print("投影矩阵性质验证")
print("=" * 60)

# 1. 对称性
print(f"P^T = P? {np.allclose(P2, P2.T)}")

# 2. 幂等性
print(f"P^2 = P? {np.allclose(P2 @ P2, P2)}")

# 3. I - P 也是投影（投影到正交补）
P_orth = np.eye(3) - P2
e = P_orth @ b
print(f"\ne = (I - P)b = {e.round(3)}")
print(f"e 和 p 正交吗？ p·e = {np.dot(p, e):.6f} (应为0)")

一维投影矩阵
a = [1 2 2]

P = (a a^T) / (a^T a) =
[[0.11111111 0.22222222 0.22222222]
 [0.22222222 0.44444444 0.44444444]
 [0.22222222 0.44444444 0.44444444]]

b = [1 1 1]
投影 p = [0.55555556 1.11111111 1.11111111]
验证: p 是 a 的倍数吗？[0.55555556 1.11111111 1.11111111]
误差 e = b - p = [ 0.44444444 -0.11111111 -0.11111111]
e·a = -2.220446049250313e-16 (应为0)

高维投影矩阵
A = 
 [[1 0]
 [1 1]
 [1 2]]
b = [1 2 2]

P = A (A^T A)^-1 A^T =
[[ 0.833  0.333 -0.167]
 [ 0.333  0.333  0.333]
 [-0.167  0.333  0.833]]

投影 p = [1.167 1.667 2.167]

投影矩阵性质验证
P^T = P? True
P^2 = P? True

e = (I - P)b = [-0.167  0.333 -0.167]
e 和 p 正交吗？ p·e = 0.000000 (应为0)
