In [1]:
import numpy as np

# ---- 定义一个矩阵 ----
A = np.array([[3, 1], [1, 2]])
print("=" * 60)
print("基变换")
print("=" * 60)
print("A (标准基下) = \n", A)

# ---- 计算特征值和特征向量 ----
eigvals, eigvecs = np.linalg.eigh(A)
print(f"\n特征值: {eigvals}")
print(f"特征向量 (新基):\n{eigvecs}")

# ---- 在新基下，A 变成对角矩阵 ----
# 新基是特征向量基，变换矩阵是 B = eigvecs
B = eigvecs
A_new = np.linalg.inv(B) @ A @ B
print(f"\n在特征向量基下，A_new = B^{-1} A B =\n{A_new.round(3)}")
print("这是一个对角矩阵！特征值在对角线上。")

# ---- 用另一个基 ----
# 选择另一个基（不是特征向量基）
B_other = np.array([[1, 1], [-1, 1]])
B_other = B_other / np.sqrt(2)  # 归一化（正交基）
A_other = np.linalg.inv(B_other) @ A @ B_other
print(f"\n在另一个基下，A_other =\n{A_other.round(3)}")
print("这个矩阵不是对角矩阵——基不是特征向量基。")

# ---- 验证：新基下的矩阵作用于新基下的向量 ----
# 在标准基下取一个向量
x_std = np.array([1, 0])
# 转换为新基下的坐标
x_new = np.linalg.inv(B) @ x_std

# 在新基下做变换
y_new = A_new @ x_new

# 转回标准基
y_std = B @ y_new

# 验证：结果和直接 A @ x_std 相同
y_std_direct = A @ x_std
print(f"\n验证:")
print(f"  A @ x_std = {y_std_direct}")
print(f"  B @ A_new @ B^{-1} @ x_std = {y_std}")
print(f"  相等？ {np.allclose(y_std_direct, y_std)}")

基变换
A (标准基下) = 
 [[3 1]
 [1 2]]

特征值: [1.38196601 3.61803399]
特征向量 (新基):
[[ 0.52573111 -0.85065081]
 [-0.85065081 -0.52573111]]

在特征向量基下，A_new = B^-1 A B =
[[ 1.382 -0.   ]
 [ 0.     3.618]]
这是一个对角矩阵！特征值在对角线上。

在另一个基下，A_other =
[[1.5 0.5]
 [0.5 3.5]]
这个矩阵不是对角矩阵——基不是特征向量基。

验证:
  A @ x_std = [3 1]
  B @ A_new @ B^-1 @ x_std = [3. 1.]
  相等？ True
